apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sllm
  template:
    metadata:
      labels:
        app: k8sllm
    spec:
      containers:
      - name: k8sllm-container
        image: dockerdu2914/k8sllm:1.0.5
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
